---
# This is the basic setup which is common across all of the various
# platform scripts
#
# This "raw" playbook provisions an EC2 Instance for use as a temporary 
# trial compile machine
#
# See: https://www.agix.com.au/build-an-ec2-using-ansible-step-by-step/
# and: https://www.linuxschoolonline.com/use-ansible-to-build-and-manage-aws-ec2-instances/

- name: Setup and install basic tools
  hosts: compileServers
  remote_user: ubuntu
  gather_facts: no
  pre_tasks:
    - name: 'install python'
      raw: 'sudo apt-get -y install python'
      become: yes
  tasks:
    - name: Update all existing packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600 # one hour
    - name: Install Test tools
      become: yes
      apt:
        state: latest
        update_cache: yes
        name:
          - aptitude
          - nginx
    - name: copy test scripts
      copy:
        src: scripts/
        dest: .
        mode: a+x
    - name: copy simple test PDF files
      copy:
        src: files/
        dest: .
