---

# This "raw" playbook provisions an EC2 Instance for use as a temporary 
# trial compile machine. This is useful for test compiling updates to 
# pdf2htmlEX while it is in development.
#
# This playbook uses the *stephengaito/pdf2htmlEX* sources from the HEAD of 
# the *master* branch.
#
# To use another *developmental* fork of pdf2htmlEX, make a *copy* of this 
# playbook and make the appropriate changes.
#

- import_playbook: basicBuildSetup.yml

- name: Setup and install poppler and pdf2htmlEX repos for compilation
  hosts: compileServers
  remote_user: ubuntu
  gather_facts: no
  tasks:
    - name: Install poppler git repo for compilation
      git:
        repo: https://gitlab.freedesktop.org/poppler/poppler.git
        dest: /home/ubuntu/poppler
        version: poppler-0.76.0
    - name: Install pdf2htmlEX git repo for compilation
      git:
        repo: https://github.com/stephengaito/pdf2htmlEX.git
        dest: /home/ubuntu/pdf2html
    - name: Install pdf2htmlEX packaging tools
      git:
        repo: https://github.com/pdf2htmlEX/buildAndPackagingTools
        dest: /home/ubuntu/pdf2html-buildAndPackagingTools
    - name: copy build_dists.py
      copy:
        src: /home/ubuntu/pdf2html-buildAndPackagingTools/packaging/build_dists.py
        remote_src: yes
        dest: /home/ubuntu/pdf2html/build_dists.py
        mode: preserve
    - name: copy debian directory
      copy:
        src: /home/ubuntu/pdf2html-buildAndPackagingTools/packaging/debian
        remote_src: yes
        dest: /home/ubuntu/pdf2html

