#!/bin/bash

# This bash script scp's the deb archive from the remote machine

mkdir -p tmp

scp -i $ANSIBLE_SSH_KEY ubuntu@$AWS1_IP:build-area/$1 tmp

scp -i $ANSIBLE_SSH_KEY                                                   \
  ubuntu@$AWS1_IP:pdf2html/debian/changelog                               \
  ../packaging/debian/changelog

cd tmp

md5sum $1 > $1.md5
sha256sum $1 > $1.sha256
