#!/bin/bash

# This bash script scp's a patch file from the remote machine

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <<ipAddress>>"
  exit -1
fi

ipaddress="$(cut -d'/' -f1 <<<$1)"

scp -i $VIRTUAL_MACHINE_SSH_KEY                       \
  $VIRTUAL_MACHINE_USER@$ipaddress:pdf2html/patchFile \
  patches

echo "NOW rename the tmp/patchFile to describe"
echo "   what date it was created on, and"
echo "   which poppler version it is associated with"
echo ""
echo "for example:"
echo "    mv patchFile 20190926-poppler-0_76_0.patch"
echo ""
