#!/bin/bash

# This bash script scp's a patch file from the remote machine

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <<ipAddress>>"
  echo ""
  echo "You can use the git command:"
  echo ""
  echo "  git add -N <<path to an untracked file>>"
  echo ""
  echo "to add an untracked file so that the command:"
  echo ""
  echo "  git diff > patchFile"
  echo ""
  echo "will provide a \"diff\" of the all of the"
  echo "tracked and untracked files."
  echo ""
  exit -1
fi

ipaddress="$(cut -d'/' -f1 <<<$1)"

scp -i $VIRTUAL_MACHINE_SSH_KEY                       \
  $VIRTUAL_MACHINE_USER@$ipaddress:pdf2html/patchFile \
  patches

echo "NOW rename the tmp/patchFile to describe"
echo "   what date it was created on, and"
echo "   which poppler version it is associated with"
echo ""
echo "for example:"
echo "    mv patchFile 20190926-poppler-0_76_0.patch"
echo ""
