#!/bin/bash

# This bash script scp's a patch file from the remote machine

scp -i $ANSIBLE_SSH_KEY ubuntu@$AWS2_IP:pdf2html/patchFile patches

echo "NOW rename the tmp/patchFile to describe"
echo "   what date it was created on, and"
echo "   which poppler version it is associated with"
echo ""
echo "for example:"
echo "    mv patchFile 20190926-poppler-0_76_0.patch"
echo ""
