#!/bin/bash

# This bash script opens the pdf2htmlEX test websites on aws0

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <<ipAddress>>"
  exit -1
fi

ipaddress="$(cut -d'/' -f1 <<<$1)"

xdg-open http://$ipaddress/testrevelatornl/testrevelatornl.html

xdg-open http://$ipaddress/joyLoL/joyLoL.html


