---

# This "raw" playbook provisions an Virtual Machine Instance for use as a 
# temporary trial compile machine. This is useful for test compiling 
# updates to pdf2htmlEX while it is in development.
#
# This playbook uses the *stephengaito/pdf2htmlEX* sources from the HEAD of 
# the *master* branch.
#
# To use another *developmental* fork of pdf2htmlEX, make a *copy* of this 
# playbook and make the appropriate changes.
#

- import_playbook: basicBuildSetup.yml

- name: Setup and install poppler and pdf2htmlEX repos for compilation
  hosts: all
  remote_user: "{{ lookup('env', 'VIRTUAL_MACHINE_USER') }}"
  gather_facts: no
  tasks:
    - name: Install poppler git repo for compilation
      git:
        repo: https://gitlab.freedesktop.org/poppler/poppler.git
        dest: poppler
        version: "{{ popplerVersion }}"
    - name: Install fontforge git repo for compilation
      git:
        repo: https://github.com/fontforge/fontforge.git
        dest: fontforge
        version: "{{ fontforgeVersion }}"
    - name: Install pdf2htmlEX git repo for compilation
      git:
        repo: "{{ pdf2htmlEXDevRepo.url }}"
        dest: pdf2html
        version: "{{ pdf2htmlEXDevRepo.version }}"
    - name: Install pdf2htmlEX packaging tools
      git:
        repo: https://github.com/pdf2htmlEX/buildAndPackagingTools
        dest: pdf2html-buildAndPackagingTools
        version: "{{ pdf2htmlEXBuildToolsVersion }}"
    - name: copy build_dists.py
      copy:
        src: pdf2html-buildAndPackagingTools/packaging/build_dists.py
        remote_src: yes
        dest: pdf2html/build_dists.py
        mode: preserve
    - name: copy debian directory
      copy:
        src: pdf2html-buildAndPackagingTools/packaging/debian
        remote_src: yes
        dest: pdf2html

